Link gitconfig

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,10 @@
 #!/bin/sh
 
+# Exit on error
+set -e
+
 DOTFILES="
+.gitconfig
 .gitignore_global
 .oh-my-zsh
 .profile
@@ -10,17 +14,12 @@ DOTFILES="
 .zshrc
 "
 
-fatal () {
-    echo >&2 "\033[31m[FATAL]\033[0m $1"
-    exit 1
+success () {
+    echo "\033[32m[OK]   \033[0m $1"
 }
 
 warn () {
     echo "\033[33m[WARN] \033[0m $1"
-}
-
-success () {
-    echo "\033[32m[OK]   \033[0m $1"
 }
 
 info () {
@@ -59,33 +58,28 @@ configure_git () {
     git config --global user.name "$name"
     git config --global user.email "$email"
 
-    git config --global push.default current
-
     git config --global core.excludesfile "$HOME/.gitignore_global"
-
-    git config --global alias.co checkout
-    git config --global alias.ci commit
-    git config --global alias.st status
-    git config --global alias.br branch
-    git config --global alias.ds diff --cached
-    git config --global alias.spu stash
-    git config --global alias.spo stash pop
-    git config --global alias.hist "log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short"
 }
 
 
-if [[ "debug" = $1 ]]; then
-    DEBUG=1
-else
-    DEBUG=0
-fi
+main () {
+    if [[ "debug" = $1 ]]; then
+        DEBUG=1
+    else
+        DEBUG=0
+    fi
 
-confirm "Running this installation will wipe all previous dotfiles."
+    confirm "Running this installation will wipe all previous dotfiles."
 
-info "Updating git submodules" && \
-    silence git submodule update --init || warn "Failed to update git modules" && \
-    link_dotfiles && \
+    info "Updating git submodules"
+    silence git submodule update --init || warn "Failed to update git modules"
+    link_dotfiles
     info "Configuring git"
-    configure_git && \
+    configure_git
     success "Dotfiles installed!"
+}
 
+
+if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
+    main "$@"
+fi
